### ISSUE TITLE
7 - Products

### ISSUE THREAD

**Issue by hagansmith** [nss-evening-cohort-06/company-x-fivealive#19]
Included information for each product.
- Product names
- Product pictures
- Product Price
- Product descriptions
  - Tether Strength
  - Material
  - Comfort(Hate) rating

**Comment by hagansmith** [comment]
JavaScript:
Items placed in ARRAY
loop through items and write to DOM

**Comment by hagansmith** [comment]
Products displayed 5 cards wide on standard computer screen
Products wrap to 3 cards on small screens

**Comment by hagansmith** [comment]
Product cards:
Border around each product card
Product name - in a heading tag with bottom border
Image - full width of container
Product price - listed at lower right corner of image
Product description(top border) -  small product blurb with, tether strength material and comfort rating

**Comment by Junochop** [comment]
looks good!
